name: website deployment
on: [push]
jobs:  
  deploy:    
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: deploy cdtest
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "dest/*"
          target: "/srv/htdocs/uhslc.soest.hawaii.edu/"
