name: website deployment
on: 
  push:
  workflow_dispatch:
jobs:  
  deploy:    
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: deploy cdtest
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "dest/*"
          target: "/srv/htdocs/uhslc.soest.hawaii.edu/cdtest"
          script: |
            whoami
            ls -al
